server:
  port: 8081 #端口
spring:
  application:
    name: api-gateway-server #服务名称



  cloud: #配置SpringCloudGateway的路由
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedHeaders: "*"
            maxAge: 360000
            allowedMethods:
              - GET
              - POST
              - DELETE
              - PUT
              - OPTION
        add-to-simple-url-handler-mapping: true


      routes:
      - id: student-service
#        uri: http://localhost:9001
        uri: lb://student-service
        predicates:
        - Path=/student/**
        - Path=/manager/**
#        - Path=/student-service/**
#        filters: # 配置路由过滤器 http://localhost:8081/student-service/student/getStudentPage
#        - RewritePath=/student-service/(?<segment>.*), /$\{segment}
      discovery:
        locator:
          enabled: true # 开启根据名称自动转发
          lower-case-service-id: true # 微服务名称已小写形式呈现
    #redis配置
  redis:
    host: 192.168.222.128
    port: 6379
    lettuce:
      pool:
        max-wait: 1000
        max-idle: 8
        min-idle: 0
        max-active: 8

eureka:
  client:
    service-url:
      defaultZone: http://eureka7005.com:7005/eureka/, http://eureka7006.com:7006/eureka/
  instance:
    prefer-ip-address: true

logging:
  level:
    root: info
    org.springframework.web.servlet.DispatcherServlet: DEBUG
    org.springframework.cloud.sleuth: DEBUG
    com.dreamer: info