server:
  port: 7005
spring:
  application:
    name: eureka-server

eureka:
  instance:
    hostname: eureka7005.com
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: http://eureka7006.com:7006/eureka/

  server:
    enable-self-preservation: false    # 自我保护机制，保护服务列表被误杀
